# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kırpıcı.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from  PIL import Image


class Ui_Form(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(776, 517)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(590, 147, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(590, 200, 161, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 240, 161, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 290, 161, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label=QtWidgets.QLabel("Resim",Form)

        self.pushButton.clicked.connect(self.klasorAc)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Resim aç"))
        self.pushButton_2.setText(_translate("Form", "Kırp"))
        self.pushButton_3.setText(_translate("Form", "Yenile"))


    def klasorAc(self):
        print("burası")
        """file_dialog= QtWidgets.QFileDialog(self)
        file_dialog.setNameFilters(["Images (*.png *.jpg)"])
        file_dialog.selectNameFilter("Images (*.png*.jpg)")
        file_dialog.exec_()"""
        #dosya_ismi=file_dialog.getOpenFileName(self,"Dosya Aç",os.getenv("HOME"))
        dosya_ismi=QtWidgets.QFileDialog.getOpenFileName(self,"Dosya Aç",os.getenv("HOME"),"*.jpg;;*.png")

        self.pixmap =QtGui.QPixmap(dosya_ismi[0])
        self.label.setPixmap(QtGui.QPixmap(self.pixmap))
        self.label.setGeometry(0,0,550,400)
        self.label.setScaledContents(True)
        self.resize(self.pixmap.width(),self.pixmap.height())
        print(dosya_ismi)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
