# Generated by Django 3.1.3 on 2020-11-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201116_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekleyiniz'),
        ),
    ]
